load("@rules_python//python:py_test.bzl", "py_test")

package(default_visibility = ["//visibility:public"])

py_test(
    name = "selftest",
    size = "small",
    srcs = ["agent_selftest.py"],
    data = [
        "start_build.sh",
        "//:conftest.py",
        "//:pytest.ini",
    ],
    main = "agent_selftest.py",
    deps = ["@pypi//pytest"],
)

py_test(
    name = "open_pr_selftest",
    size = "small",
    srcs = ["open_pr_selftest.py"],
    data = [
        "open_pr.sh",
        "//:conftest.py",
        "//:pytest.ini",
    ],
    main = "open_pr_selftest.py",
    deps = ["@pypi//pytest"],
)

filegroup(
    name = "py_srcs",
    srcs = glob(["*.py"]),
)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**"],
        exclude = ["**/__pycache__/**"],
    ),
    visibility = ["//:__pkg__"],
)
