"""Rewrites the golden contract listing, refusing breaking changes. See docs/guardrails.md."""

import os
import sys

from google.protobuf import descriptor_pb2
from python.runfiles import runfiles

from tools.proto_compat.compat import breaking_changes, describe, read_listing

GOLDEN = "proto/recommender.fields.golden"


def main() -> int:
    r = runfiles.Create()
    if r is None:
        print("runfiles not found", file=sys.stderr)
        return 1
    descriptor = r.Rlocation(f"_main/{sys.argv[1]}")
    if descriptor is None:
        print(f"descriptor set {sys.argv[1]} not found in runfiles", file=sys.stderr)
        return 1
    fds = descriptor_pb2.FileDescriptorSet()
    with open(descriptor, "rb") as f:
        fds.ParseFromString(f.read())
    current = describe(fds)
    golden_path = os.path.join(os.environ["BUILD_WORKSPACE_DIRECTORY"], GOLDEN)
    golden: list[str] = []
    if os.path.exists(golden_path):
        with open(golden_path, encoding="utf-8") as f:
            golden = read_listing(f.read())
    broken = breaking_changes(golden, current)
    if broken:
        print("Refusing to update: the change is breaking.", file=sys.stderr)
        for b in broken:
            print(f"  - {b}", file=sys.stderr)
        return 1
    with open(golden_path, "w", encoding="utf-8") as f:
        f.write("// Generated by bazel run //tools/proto_compat:update_golden. Do not edit.\n")
        f.write("\n".join(current) + "\n")
    print(f"wrote {GOLDEN}: {len(current)} facts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
