load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "items",
    srcs = [
        "__init__.py",
        "items.py",
    ],
)

py_library(
    name = "registry",
    srcs = ["registry.py"],
)

py_library(
    name = "targets",
    srcs = ["targets.py"],
    deps = [
        ":items",
        ":registry",
    ],
)
